version: "3.9" # optional since v1.27.0
services:
  rdatascience:
    image: joundso/rdsc_rstudio_j:${VERSION_TAG}
    restart: unless-stopped
    ports:
    - "${RSTUDIO_PORT}:8787" #rstudio
    - "${SHINY_PORT}:3838" #shiny
    # https://github.com/rocker-org/rocker-versioned/blob/master/user/README.md
    environment:
    - DISPLAY=$IP:0
    volumes:
    ## work:
    - /d/Docker/container/docker-share/R:/home/user/share
    - /d/git-local:/home/user/git-local
    - /d/_p21/:/home/user/p21
    ## home:
    # - /k/Docker/docker-share/R:/home/user/share
    # - /d/git-local:/home/user/git-local
    tty: true
    privileged: true
